version: '3.8'
services:
  db:
    image: postgres:15
    container_name: nenufar_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nenufar
    ports:
      - "5433:5432"   # si ya usas 5432 en tu Mac, cambia a "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
